import { StyleSheet } from "react-native";
import { colors, fonts, radius, shadow } from "../lib/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F5F8",
  },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F4F5F8",
  },

  headerTitle: {
    fontFamily: fonts.heading,
    fontSize: 26,
    color: "#FFFFFF",
    letterSpacing: -0.3,
  },
  headerSub: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: "rgba(255,255,255,0.78)",
    marginTop: 4,
  },

  body: {
    paddingHorizontal: 18,
    marginTop: -46,
    paddingBottom: 110,
    gap: 14,
  },

  profilCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radius.xl,
    padding: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow.card,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 999,
    backgroundColor: colors.teal,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  avatarText: {
    fontFamily: fonts.heading,
    fontSize: 28,
    color: "#0E1210",
  },
  profilNom: {
    fontFamily: fonts.heading,
    fontSize: 18,
    color: colors.textPrimary,
    marginBottom: 2,
  },
  profilEmail: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 6,
  },
  profilPoint: {
    fontFamily: fonts.bodySemiBold,
    fontSize: 12,
    color: colors.tealDark,
    backgroundColor: colors.tealBg,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: radius.full,
    marginTop: 2,
  },

  sectionTitle: {
    fontFamily: fonts.body,
    fontSize: 11,
    color: colors.textLabel,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 8,
    marginLeft: 4,
  },

  menuCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
    ...shadow.card,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
    gap: 14,
  },
  menuItemLast: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    gap: 14,
  },
  menuIcon: {
    width: 38,
    height: 38,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  menuContent: {
    flex: 1,
  },
  menuLabel: {
    fontFamily: fonts.bodySemiBold,
    fontSize: 14,
    color: colors.textPrimary,
  },
  menuSub: {
    fontFamily: fonts.body,
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },

  deconnexionBtn: {
    backgroundColor: colors.redBg,
    borderRadius: radius.xl,
    padding: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.red + "40",
  },
  deconnexionText: {
    fontFamily: fonts.bodySemiBold,
    fontSize: 15,
    color: colors.red,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.5)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: colors.bgCard,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
    gap: 4,
  },
  modalTitle: {
    fontFamily: fonts.heading,
    fontSize: 18,
    color: colors.textPrimary,
    marginBottom: 16,
  },
  modalLabel: {
    fontFamily: fonts.body,
    fontSize: 11,
    color: colors.textLabel,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 6,
    marginTop: 8,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: colors.borderInput,
    borderRadius: radius.md,
    padding: 14,
    fontFamily: fonts.body,
    fontSize: 14,
    color: colors.textPrimary,
    backgroundColor: colors.bgInput,
    marginBottom: 4,
  },
  modalBtn: {
    borderRadius: radius.lg,
    padding: 15,
    alignItems: "center",
    marginTop: 8,
  },
  modalBtnText: {
    fontFamily: fonts.bodySemiBold,
    color: "#0E1210",
    fontSize: 15,
  },
  modalBtnOutline: {
    borderWidth: 1,
    borderColor: colors.borderInput,
    borderRadius: radius.lg,
    padding: 14,
    alignItems: "center",
    marginTop: 8,
  },
  modalBtnOutlineText: {
    fontFamily: fonts.bodySemiBold,
    color: colors.textSecondary,
    fontSize: 15,
  },

  alertError: {
    backgroundColor: colors.redBg,
    borderRadius: radius.md,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.red + "40",
  },
  alertErrorText: {
    fontFamily: fonts.body,
    color: colors.red,
    fontSize: 13,
  },
  alertSuccess: {
    backgroundColor: colors.greenBg,
    borderRadius: radius.md,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.green + "40",
  },
  alertSuccessText: {
    fontFamily: fonts.body,
    color: colors.green,
    fontSize: 13,
  },
});
