import { StyleSheet } from "react-native";
import { colors, fonts, radius, shadow } from "../../lib/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bgPage,
  },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.bgPage,
  },

  // HERO
  hero: {
    paddingTop: 56,
    paddingHorizontal: 24,
    paddingBottom: 100,
    overflow: "hidden",
  },
  heroBubble1: {
    position: "absolute",
    top: -60,
    right: -40,
    width: 200,
    height: 200,
    borderRadius: radius.full,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  heroBubble2: {
    position: "absolute",
    top: 70,
    right: 90,
    width: 90,
    height: 90,
    borderRadius: radius.full,
    backgroundColor: "rgba(255,255,255,0.06)",
  },

  // HEADER
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 24,
  },
  headerGreeting: {
    fontFamily: fonts.body,
    fontSize: 14,
    color: "rgba(255,255,255,0.82)",
    marginBottom: 3,
  },
  headerName: {
    fontFamily: fonts.heading,
    fontSize: 30,
    color: "#FFFFFF",
    letterSpacing: -0.3,
  },
  headerSub: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: "rgba(255,255,255,0.78)",
    marginTop: 4,
  },
  avatarBtn: {
    width: 46,
    height: 46,
    borderRadius: radius.full,
    backgroundColor: "rgba(255,255,255,0.18)",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.45)",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    fontFamily: fonts.heading,
    fontSize: 17,
    color: "#FFFFFF",
  },

  // GLASS CARD COTISATION
  glassCard: {
    backgroundColor: "rgba(255,255,255,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    borderRadius: 20,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
  },
  glassLabel: {
    fontFamily: fonts.bodySemiBold,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.8)",
    marginBottom: 7,
  },
  glassVal: {
    fontFamily: fonts.heading,
    fontSize: 24,
    color: "#FFFFFF",
  },
  glassPayerBtn: {
    marginTop: 10,
    backgroundColor: "rgba(255,255,255,0.25)",
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: radius.full,
    alignSelf: "flex-start",
  },
  glassPayerText: {
    fontFamily: fonts.bodySemiBold,
    fontSize: 13,
    color: "#FFFFFF",
  },
  glassRight: {
    alignItems: "center",
    gap: 4,
  },
  glassCheck: {
    width: 44,
    height: 44,
    borderRadius: radius.full,
    backgroundColor: "rgba(255,255,255,0.92)",
    alignItems: "center",
    justifyContent: "center",
  },
  glassCheckLabel: {
    fontFamily: fonts.bodySemiBold,
    fontSize: 11,
    color: "rgba(255,255,255,0.9)",
  },

  // BODY
  body: {
    paddingHorizontal: 18,
    marginTop: -86,
    gap: 14,
  },

  // BANNIÈRES
  bannerOffline: {
    backgroundColor: colors.redBg,
    borderWidth: 1,
    borderColor: "rgba(251,113,133,0.3)",
    borderRadius: radius.lg,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  bannerOfflineTitle: {
    fontFamily: fonts.bodySemiBold,
    fontSize: 13,
    color: colors.red,
  },
  bannerAttente: {
    backgroundColor: colors.amberBg,
    borderWidth: 1,
    borderColor: "rgba(251,191,36,0.3)",
    borderRadius: radius.lg,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  bannerAttenteTitle: {
    fontFamily: fonts.bodySemiBold,
    fontSize: 13,
    color: "#D97706",
  },
  bannerSub: {
    fontFamily: fonts.body,
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },

  // STATS
  statsRow: {
    flexDirection: "row",
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.xl,
    padding: 16,
    ...shadow.card,
  },
  statIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  statVal: {
    fontFamily: fonts.heading,
    fontSize: 26,
    lineHeight: 28,
  },
  statLabel: {
    fontFamily: fonts.body,
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 3,
  },

  // POINT DE COLLECTE
  pointCard: {
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.xl,
    padding: 20,
    ...shadow.card,
  },
  pointLabel: {
    fontFamily: fonts.bodySemiBold,
    fontSize: 11,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: colors.textLabel,
    marginBottom: 12,
  },
  pointRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  pointNom: {
    fontFamily: fonts.heading,
    fontSize: 21,
    color: colors.textPrimary,
    lineHeight: 26,
    letterSpacing: -0.3,
  },
  pointSecteur: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 4,
  },
  statutBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: radius.full,
    flexShrink: 0,
  },
  statutDot: {
    width: 6,
    height: 6,
    borderRadius: radius.full,
  },
  statutText: {
    fontFamily: fonts.bodySemiBold,
    fontSize: 12,
  },
  barRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
    marginBottom: 9,
  },
  barLabel: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.textSecondary,
  },
  barPct: {
    fontFamily: fonts.headingSemiBold,
    fontSize: 16,
    color: colors.teal,
  },
  barTrack: {
    height: 8,
    borderRadius: radius.full,
    backgroundColor: colors.border,
    overflow: "hidden",
  },

  // CTA
  cta: {
    position: "relative",
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
    padding: 18,
    borderRadius: 20,
    shadowColor: colors.teal,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.38,
    shadowRadius: 30,
    elevation: 10,
  },
  ctaDisabled: {
    opacity: 0.6,
  },
  ctaBubble: {
    position: "absolute",
    top: -30,
    right: -20,
    width: 120,
    height: 120,
    borderRadius: radius.full,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  ctaIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 15,
    backgroundColor: "rgba(255,255,255,0.22)",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    zIndex: 1,
  },
  ctaTitle: {
    fontFamily: fonts.heading,
    fontSize: 17,
    color: "#FFFFFF",
  },
  ctaSub: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: "rgba(255,255,255,0.85)",
    marginTop: 2,
  },

  // MODAL
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.5)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: colors.bgCard,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    gap: 12,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: colors.borderLight,
    borderRadius: radius.full,
    alignSelf: "center",
    marginBottom: 4,
  },
  modalIcon: {
    width: 64,
    height: 64,
    borderRadius: radius.full,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  modalTitle: {
    fontFamily: fonts.heading,
    fontSize: 20,
    color: colors.textPrimary,
    textAlign: "center",
  },
  modalSub: {
    fontFamily: fonts.body,
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: "center",
  },
  modalInfo: {
    backgroundColor: colors.bgPage,
    borderRadius: radius.lg,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  modalInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  modalInfoRowLast: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 7,
  },
  modalInfoLabel: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.textSecondary,
  },
  modalInfoVal: {
    fontFamily: fonts.bodySemiBold,
    fontSize: 13,
    color: colors.textPrimary,
  },
  modalBtn: {
    borderRadius: radius.lg,
    paddingVertical: 15,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  modalBtnText: {
    fontFamily: fonts.bodySemiBold,
    fontSize: 15,
    color: "#0E1210",
  },
  modalBtnOutline: {
    borderRadius: radius.lg,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.borderInput,
  },
  modalBtnOutlineText: {
    fontFamily: fonts.bodySemiBold,
    fontSize: 15,
    color: colors.textSecondary,
  },
});
